name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Prepare deploy folder
        run: |
          mkdir deploy
          cp -r dist deploy/dist
          cp -r games deploy/games
          cp -r zgamesPicrtures deploy/zgamesPicrtures
          cp index.html deploy/index.html
          cp index.css deploy/index.css
          cp index.js deploy/index.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy